# Generated by Django 3.2.5 on 2021-11-07 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkloadStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250)),
                ('status', models.CharField(choices=[('done', 'done'), ('pending', 'pending'), ('cancelled', 'cancelled')], max_length=50)),
                ('workload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workload.workload')),
            ],
        ),
    ]
