# Generated by Django 3.2.8 on 2021-11-11 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload', '0002_workloadstep'),
    ]

    operations = [
        migrations.AddField(
            model_name='workload',
            name='workload_url',
            field=models.CharField(default='https://google.com', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workloadstep',
            name='status',
            field=models.CharField(choices=[('done', 'done'), ('pending', 'pending'), ('error', 'error')], max_length=50),
        ),
    ]
