# Generated by Django 3.2.8 on 2021-11-24 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workload', '0003_auto_20211111_0845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workload',
            old_name='unit',
            new_name='cpu',
        ),
        migrations.RenameField(
            model_name='workload',
            old_name='cloud_name',
            new_name='family',
        ),
        migrations.RenameField(
            model_name='workload',
            old_name='machine_type',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='workload',
            old_name='tester',
            new_name='network_mode',
        ),
    ]
