# Generated by Django 3.2.8 on 2021-10-27 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('workload_name', models.CharField(max_length=100)),
                ('tester', models.CharField(max_length=50)),
                ('cloud_name', models.CharField(max_length=30)),
                ('machine_type', models.CharField(max_length=50)),
                ('platform', models.CharField(max_length=100)),
                ('metric', models.CharField(choices=[('optimal', 'optimal'), ('total', 'total'), ('rate', 'rate'), ('max', 'max')], max_length=50)),
                ('value', models.IntegerField()),
                ('unit', models.CharField(max_length=10)),
                ('tags', models.CharField(max_length=20)),
            ],
        ),
    ]
